# Generated by Django 2.2.3 on 2019-07-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('next_question', models.PositiveSmallIntegerField()),
                ('water_used', models.DecimalField(blank=True, decimal_places=2, help_text='Water used in litres', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('order', models.PositiveSmallIntegerField()),
                ('bg_desktop1', models.CharField(blank=True, max_length=1000)),
                ('bg_desktop2', models.CharField(blank=True, max_length=1000)),
                ('bg_desktop3', models.CharField(blank=True, max_length=1000)),
                ('bg_desktop4', models.CharField(blank=True, max_length=1000)),
                ('bg_desktop5', models.CharField(blank=True, max_length=1000)),
                ('bg_mobile1', models.CharField(blank=True, max_length=1000)),
                ('bg_mobile2', models.CharField(blank=True, max_length=1000)),
                ('Option_type', models.CharField(choices=[('CH', 'Radio'), ('BU', 'Button'), ('RA', 'Range for minutes'), ('RA-S', 'Range for size of bucket'), ('RA-L', 'Range for Litres(0-30)'), ('RA-B', 'Range for Number of Buckets'), ('RA-T', 'Range for number of times'), ('RA-LB', 'Range for Litres big(0-100)'), ('RA-Area', 'Range for Area of garden'), ('RA-Pets', 'Range for number of pets')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(editable=False, max_length=100)),
                ('total_water_usage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='question_wise_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_used', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Options')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.CreateModel(
            name='category_wise_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_usage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
