# Generated by Django 2.2.3 on 2019-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bg_mobile3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
